repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: mixed-line-ending
        args: ["--fix=lf"]
        exclude: ^aida/document/msg_support.py
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.131
    hooks:
      - id: ruff
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
