[package]
name = "renpyfmt"
version = "0.1.0"
edition = "2021"

[dependencies]
# System
regex = "1.10.3"
anyhow = "1.0.79"
pathdiff = "0.2.1"
derivative = "2.2.0"
glob = "0.3.1"
rayon = "1.8.1"
# Ruff
# ruff_python_formatter = { git = "https://github.com/astral-sh/ruff.git", tag = "v0.1.14" }
# ruff_text_size = { git = "https://github.com/astral-sh/ruff.git", tag = "v0.1.14", version = "0.0.0" }
# ruff_formatter = { git = "https://github.com/astral-sh/ruff.git", tag = "v0.1.14", version = "0.0.0" }
# ruff_python_ast = { git = "https://github.com/astral-sh/ruff.git", tag = "v0.1.14", version = "0.0.0" }
# ruff_python_index = { git = "https://github.com/astral-sh/ruff.git", tag = "v0.1.14", version = "0.0.0" }
# ruff_python_parser = { git = "https://github.com/astral-sh/ruff.git", tag = "v0.1.14", version = "0.0.0" }

[profile.release]
lto = "thin"
strip = true
