name: Build

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    container: python:3.11
    steps:
      - uses: actions/checkout@v3
      - name: Install project
        run: |
          pip install poetry
          poetry install
      - name: Run pre-commit
        run: |
          ls -al
          git config --systemt --add safe.directory /__w/renpyfmt/renpyfmt
          git status
          poetry run pre-commit run -a

  upload-release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [lint]
    runs-on: ubuntu-latest
    container: python:3.11
    steps:
      - uses: actions/checkout@v3
      - name: Install project
        run: |
          pip install poetry
          poetry install
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v1.16
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN }}
